---
title: "FixedPoints"
author: "Paul M"
date: "1/31/2020"
output: 
#rmarkdown::github_document
  html_document: default
  pdf_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This code implements the fixed-point algorithm from week 3 of class.


First let's define some functions to test it on:
```{r functions}
#  the function sqrt(10*x+1)
F1<-function(x){
	if (x<= -1){
	cat("Function not defined for x<-1. Exit.")
	return("NaN") }
		return(sqrt(10*x+1))
}

# the function x+log(x)-exp(-x)
F2<-function(x){
  return(x+log(x)-exp(-x))
}
```

Let's see what those functions look like using R's "curve" function:
```{r curves}
curve(sqrt(10*x+1),0,20,main="y=sqrt(10*x+1)")
abline(coef=c(0,1),col=4)

curve(x+log(x)-exp(-x),0,20,main="y=x+log(x)-exp(-x)")
abline(coef=c(0,1),col=4)
```

Now we write the function that will find the fixed points. It will also draw the path it takes. To do this I used the "arrows" command from the package "shape"
```{r finder}
#install.packages("shape")   # you will need to install this package if you don't have it already
library(shape)
FixedPointFinder<-function(func,StartingValue,Tolerance,MaxNumberOfIterations,DrawLines){
	# set initial parameters (maximum number of steps; accuracy required; start 	point)
	#StartingXValue<- StartValue
	#MaxNumberOfIterations<-100
	#Tolerance<-1e-5
	Deviation<-1000   # an arbitrary big number
	i<-0
	Xprime<-StartingValue 
	#browser()
	#Set up a while loop until we hit the required target accuracy or the max. 	number of steps
	while ((i<MaxNumberOfIterations)&&(Deviation>Tolerance))
	{
		# Set x'=f(x)
		X<-Xprime # x is our current v-value
		Xprime<-func(X)
		if (Xprime=="NaN"){
			cat("Function not defined error.\n")
			break
		}
		if (DrawLines){
			Arrows(X,X,X,Xprime,col="blue",lty=2,arr.length=0.25)
			Arrows(X,Xprime,Xprime,Xprime,col="blue",lty=2,arr.length=0.25)
			}
		
		# calculate accuracy<- |f(x)-x|
		Deviation<-abs(Xprime-X)
		X<-Xprime
		i<-i+1
	}

	# output the result
	if (Deviation<Tolerance){
		cat(paste("\nFound the fixed point: ",X, "after ", i, "iterations"))
		}else{
		cat(paste("\nConvergence failure. Deviation: ",Deviation, "after ", i, 	"iterations"))}
}
```

How does it do?...
```{r tests}
curve(sqrt(10*x+1),0,20,main="y=sqrt(10*x+1)")
abline(0,1)
FixedPointFinder(F1,1,1e-5,25,1)

curve(x+log(x)-exp(-x),0,20,main="y=x+log(x)-exp(-x)")
abline(coef=c(0,1),col=4)
FixedPointFinder(F2,5,1e-5,25,1)
```
